pipeline {
    agent any

    environment {
        K6_SCRIPT = 'scripts/stress_postlogin_test_copy.js'

        // ── Jira Config ── Fill these in ──────────────────────
        JIRA_BASE_URL    = "https://milesmasterclass.atlassian.net"
        JIRA_PROJECT_KEY = "MAS"
        JIRA_ISSUE_TYPE  = "Task"
        JIRA_USER_EMAIL  = "manoj.hr@mileseducation.com"
        JIRA_API_TOKEN   = credentials('jira-api-token')  // add this in Jenkins credentials
    }


    stages {

    //     stage('Checkout Code') {
    //         steps {
    //             git branch: 'main',
    //                 url: 'https://github.com/mn1809/K6PerformanceTesting.git'
    //         }
    //     }

        stage('Verify k6') {
            steps {
                bat 'k6 version'
            }
        }

        stage('Run k6 Test') {
            steps {
                // Runs K6 and saves console log + summary JSON
                //bat "k6 run ${K6_SCRIPT} 2>&1 | tee k6-console.log"

        // ✅ REPLACE with this (Windows compatible)
                bat "k6 run ${K6_SCRIPT} > k6-console.log 2>&1"
                bat "type k6-console.log"  // prints the log to Jenkins console
            }
        }

        stage('Create Jira Ticket') {
            steps {
                script {

                    // ── 1. Read summary JSON generated by handleSummary ──
                    def summaryFile = readFile('k6-summary.json')
                    def summary     = readJSON text: summaryFile
                    def metrics     = summary.metrics

                    // ── 2. Extract metrics ───────────────────────────────
                    def p95         = metrics?.http_req_duration?.values?.'p(95)' ?: "N/A"
                    def p99         = metrics?.http_req_duration?.values?.'p(99)' ?: "N/A"
                    def avgDuration = metrics?.http_req_duration?.values?.avg      ?: "N/A"
                    def errorRate   = metrics?.http_req_failed?.values?.rate       ?: 0
                    def totalReqs   = metrics?.http_reqs?.values?.count            ?: "N/A"
                    def rps         = metrics?.http_reqs?.values?.rate             ?: "N/A"
                    def vus         = metrics?.vus_max?.values?.max                ?: "N/A"

                    // ── 3. Determine pass/fail & priority ────────────────
                    //def errorPct = Math.round(errorRate * 10000) / 100.0
                    def errorPct = String.format("%.2f", (errorRate * 100) as Double)
                    def status      = (errorRate > 0.05) ? "FAILED" : "PASSED"
                    def priority    = (errorRate > 0.05) ? "High"   : "Low"

                    // ── 4. Read console log ──────────────────────────────
                    def consoleLog  = readFile('k6-console.log')
                    if (consoleLog.length() > 20000) {
                        consoleLog = consoleLog.take(20000) + "\n\n... [truncated - see Jenkins build for full log]"
                    }

                    // ── 5. Build ticket details ──────────────────────────
                    def today       = new Date().format("yyyy-MM-dd")
                    def ticketTitle = "[K6 Performance] Daily Run - ${today} | ${status}"

                    def description = """[K6 Performance Test Report - ${today}]

Build URL : ${env.BUILD_URL}
Build No  : ${env.BUILD_NUMBER}
Status    : ${status}

--- KEY METRICS ---
Avg Response Time : ${avgDuration.toString().take(6)} ms
p95 Response Time : ${p95.toString().take(6)} ms
p99 Response Time : ${p99.toString().take(6)} ms
Error Rate        : ${errorPct}%
Total Requests    : ${totalReqs}
Requests/sec      : ${rps.toString().take(6)}
Max VUs           : ${vus}

--- CONSOLE OUTPUT ---
${consoleLog}"""

                    // ── 6. Write payload to a temp file (avoids Windows quote issues) ──
                    def payload = groovy.json.JsonOutput.toJson([
                        fields: [
                            project    : [key: env.JIRA_PROJECT_KEY],
                            summary    : ticketTitle,
                            description: description,
                            issuetype  : [name: env.JIRA_ISSUE_TYPE],
                            priority   : [name: priority],
                            assignee   : [accountId: "712020:77c909ec-cc75-43dc-b5af-c154028517b0"],
                            labels     : ["k6", "performance", "automated", "daily-run"]
                        ]
                    ])
                    writeFile file: 'jira-payload.json', text: payload

                    // ── 7. Call Jira API using the payload file ───────────
                    def httpStatus = bat(
                        script: """
                            curl -s -o jira-response.json -w "%%{http_code}" ^
                                 -X POST ^
                                 -H "Content-Type: application/json" ^
                                 -H "Accept: application/json" ^
                                 -u "${env.JIRA_USER_EMAIL}:${env.JIRA_API_TOKEN}" ^
                                 --data @jira-payload.json ^
                                 "${env.JIRA_BASE_URL}/rest/api/2/issue"
                        """,
                        returnStdout: true
                    ).trim()

                    // ── 8. Log the result ────────────────────────────────
                    def jiraResp = readFile('jira-response.json')
                    if (httpStatus.contains("201")) {
                        def respJson = readJSON text: jiraResp
                        echo "✅ Jira ticket created: ${env.JIRA_BASE_URL}/browse/${respJson.key}"
                    } else {
                        echo "⚠️ Jira API returned: ${httpStatus}"
                        echo "Response: ${jiraResp}"
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'logs/**, k6-console.log, k6-summary.json', allowEmptyArchive: true
        }

        failure {
            echo '❌ k6 test failed'
        }

        success {
            echo '✅ k6 test completed successfully'
        }
    }
}



// pipeline {
//     agent any

//     environment {
//         K6_SCRIPT = 'scripts/stress_postlogin_test_copy.js'
//     }

//         stages {

//     //     stage('Checkout Code') {
//     //         steps {
//     //             git branch: 'main',
//     //                 url: 'https://github.com/mn1809/K6PerformanceTesting.git'
//     //         }
//     //     }

//         stage('Verify k6') {
//             steps {
//                 bat 'k6 version'
//             }
//         }

//         stage('Run k6 Test') {
//             steps {
//                 bat "k6 run ${K6_SCRIPT}"
//             }
//         }
//     }

//     post {
//         always {
//             archiveArtifacts artifacts: 'logs/**', allowEmptyArchive: true
//         }

//         failure {
//             echo '❌ k6 test failed'
//         }

//         success {
//             echo '✅ k6 test completed successfully'
//         }
//     }
// }